config/routes.rb
Rails.application.routes.draw do

  root 'maze_levels#index'
  resources :maze_levels

end

app/models/maze_level.rb
class MazeLevel < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maze_levels_controller.rb
class MazeLevelsController < ApplicationController
  before_action :set_maze_level, only: [:show, :edit, :update, :destroy]

  # GET /maze_levels
  # GET /maze_levels.json
  def index
  end

  # GET /maze_levels/1
  # GET /maze_levels/1.json
  def show
  end

  # GET /maze_levels/new
  def new
    @maze_level = MazeLevel.new
  end

  # GET /maze_levels/1/edit
  def edit
  end

  # POST /maze_levels
  # POST /maze_levels.json
  def create
    @maze_level = MazeLevel.new(maze_level_params)

    respond_to do |format|
      if @maze_level.save
        format.html { redirect_to @maze_level, notice: 'Maze level was successfully created.' }
        format.json { render :show, status: :created, location: @maze_level }
      else
        format.html { render :new }
        format.json { render json: @maze_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maze_levels/1
  # PATCH/PUT /maze_levels/1.json
  def update
    respond_to do |format|
      if @maze_level.update(maze_level_params)
        format.html { redirect_to @maze_level, notice: 'Maze level was successfully updated.' }
        format.json { render :show, status: :ok, location: @maze_level }
      else
        format.html { render :edit }
        format.json { render json: @maze_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maze_levels/1
  # DELETE /maze_levels/1.json
  def destroy
    @maze_level.destroy
    respond_to do |format|
      format.html { redirect_to maze_levels_url, notice: 'Maze level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maze_level
      @maze_level = MazeLevel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maze_level_params
      params[:maze_level].permit(:start_posH,:start_posV,:finish_posH, :finish_posV)
    end
end

app/controllers/web_socket_controller.rb
class WebSocketController < WebsocketRails::BaseController
  def initialize_session
    # perform application setup here
    controller_store[:message_count] = 0
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maze_levels_helper.rb
module MazeLevelsHelper
end

app/helpers/web_socket_helper.rb
module WebSocketHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codemenao</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/maze_levels/_form.html.erb
<%= form_for(@maze_level) do |f| %>
  <% if @maze_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maze_level.errors.count, "error") %> prohibited this maze_level from being saved:</h2>

      <ul>
      <% @maze_level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maze_levels/edit.html.erb
<h1>Editing Maze Level</h1>

<%= render 'form' %>

<%= link_to 'Show', @maze_level %> |
<%= link_to 'Back', maze_levels_path %>

app/views/maze_levels/index.html.erb
<div id="blocklyDiv"></div>

<script>
    var toolbox = '<xml>';
    toolbox += ' <block type="move_forward" ></block>'
    toolbox += ' <block type="turn_left" ></block>';
    toolbox += ' <block type="turn_right" ></block>';
    toolbox += ' <block type="controls_repeat_3"> </block>';
    toolbox += ' <block type="controls_repeat_2"> </block>';
    toolbox += '</xml>';
    var workspace = Blockly.inject('blocklyDiv', {toolbox: toolbox});
</script>

<div class="col-2">.</div>
<div class="col-8">
    <input type="button" value="Запустить" class='runCodeBtn'>
    <input type="button" value="Очистить"  class='clearEditor' onclick='clearEditor()' >
    <span class="congrats">Поздравляем! Робот выполняет ваши команды</span>
</div>

app/views/maze_levels/new.html.erb
<h1>New Maze Level</h1>

<%= render 'form' %>

<%= link_to 'Back', maze_levels_path %>